{% set version = "1.1.0" %}

package:
  name: humanize
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanize/humanize-{{ version }}.tar.gz
  sha256: ad83016fae2453a7486f5be5dba8e19883020c77f6c12c63702f3b6c15ae3c5e 
build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - freezegun
  commands:
    - pip check
    - pytest -v tests
  imports:
    - humanize

about:
  home: https://github.com/jmoiron/humanize
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: Python humanize utilities
  description: |
    This modest package contains various common humanization utilities, 
    like turning a number into a fuzzy human-readable duration ("3 minutes ago") 
    or into a human-readable size or throughput.
  dev_url: https://github.com/python-humanize/humanize
  doc_url: https://humanize.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ocefpaf
