{% set version = "2.6.0" %}
package:
  name: humanize
  version: {{ version }}

source:
  fn: humanize-{{ version }}.tar.gz
  url: https://github.com/jmoiron/humanize/archive/{{ version }}.tar.gz
  sha256: 9b6b0b012f1088588483e9bf126d542e545eb46f24f9297ef0769cd35be4038e

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - pkg_resources
    - python

test:
  imports:
    - humanize

about:
  home: https://github.com/jmoiron/humanize
  license: MIT
  license_file: LICENCE
  summary: 'Python humanize utilities.'

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ocefpaf
