{% set version = "4.12.2" %}

package:
  name: humanize
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanize/humanize-{{ version }}.tar.gz
  sha256: ce0715740e9caacc982bb89098182cf8ded3552693a433311c6a4ce6f4e12a2c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - wheel
    - hatch-vcs
    - hatchling >=1.27
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - humanize

about:
  home: https://github.com/python-humanize/humanize
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: Python humanize utilities
  description: |
    humanize is a Python library that provides a set of utilities for converting
    data into human-readable formats. It includes functions for formatting
    numbers, dates, and times in a way that is easy to read and understand.
  dev_url: https://github.com/python-humanize/humanize
  doc_url: https://github.com/python-humanize/humanize/blob/main/docs/index.md

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ocefpaf
