{% set version = "4.2.0" %}

package:
  name: humanize
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanize/humanize-{{ version }}.tar.gz
  sha256: b79797c101f274a19ed7b5f0cd3aa65e1aa379868b974692a9d3129ccc311be2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=3.4
    - toml
    - setuptools >=42
    - wheel
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - humanize

about:
  home: https://github.com/jmoiron/humanize
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: Python humanize utilities
  dev_url: https://github.com/jmoiron/humanize
  doc_url: https://github.com/jmoiron/humanize/blob/master/docs/index.md

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ocefpaf
