travis:
  secure:
    BINSTAR_TOKEN: uYfxQ9Ng2EsZrpOUopizxmo8FOC7rQs3j8G6m8TlqjhEiDkY8DtwtPScMVLK8IsxyphZlBC6PftPqnGK0uicGnh0YcrRje3EnX2UJieTao7u3RLYllpevSTken+i2kZWqY+1JAiRBoWWk5Jvcfmv9TmsEukePBLdKJPila9K3/of0TInQYE0XLNfy4X9Fn7GZKrUmRguqL9phRV0mxuOUr6lF+rNl6GRn+IaD7BAAs8D6K0wd/bCfowdRwAf2Sczx4ib9b95ZtiXG3cpGvUqyJIhWyFKMBIQr9LRGfdSqEDEBeYAZqOIZuo/+B0vCny1tJcQN9nZawcLv0uq+2KzhlAY3X6NriLqj9Y55FGHN+iA8bvMaLNZ+paR0ehW1v2KcjwQDkwjsoXHMy+uxfMy/mlCid0M58Ih57MC6O4lo51RRa5uywntRvZBoMsp29bYCGUoFsEQNt76kbaSuykuIxh4Ot1nv4qftNw92Uz9N1fBJPTiOP4EaWBh4C9ZwWmWtvLxFdNs3HZ+qZ692EycxuqEdnFYmYR02eaqI/Kzcj5LiusrmTkPKtl6En2028rrFGvOZO9zXSengodUp9wObDJ0ty5aBN2d1NarubxNbqeICqpJkPpftGY7RE2EFhxaLGb6h3Bylc+vdLiEBu/lnyY3Z5NmcKOJBmdaJr9enNw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
