travis:
  secure:
    BINSTAR_TOKEN: nOj1LIfXONgOW4SQqlACzEKcwp72MIpBviCVhl74Q5G9uS5Zfz2KifsRB4LorComd9M+oRTkLPvi/UL58RXPEf2LMhdKAx12jvmzqLeNOSG7qaQZyuQYTgjoXK1yydBFb37k2oeTymdqclD7ea/hTZs5IOAMkF6RsIypW6T+zewvleb0fGJtRcyHFIXaDkZ8amGSuIN8xDFaboCZpo7ZQhtY7KAjL6XSqEfvgPfqhxwYkjG82L+mBanurFGlejIns0h60DZVnMc6AtC6nuRkkNjXA84wo+2T+G61PFDjFFCh6tYRDVt2OWCCi+FDxwir0eg6wq9zUbsLozarN3zi5ND1FRMTdDCS1L9v4jsx++i00PgjyyLuH2xZ94nPx1zNpKw9XbTa8UfAN2FEYjvFmR0Oz99YgKigUIxzKwvjCpOczlnYk5qvEr7BB0+t7XxFJqu+mhRK1gao4BvA2aaiJ86kwd0LXgsQOOUKPptZY4qPOWVywNQvL4O26cQFWtvRsLFn9xsFKMvbnI6Pn6gm0U4UNjo632sPLc1H7SRmA9kyK6XTidN255AN6Eq52lmYiPSPrM5VlPE5rjcm99rV6Je0Tl5UXBiE8H8mbskVvS+do5FDX5TQ/ans2RLDo9lZbqeqWDIdZUTRXiWTgdIE0cLd+7FgDYqVkzwtVz7y6lk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
